import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/SessionProvider";
import AuthProvider from "@/components/AuthProvider";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Toaster } from 'react-hot-toast'
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${outfit.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-outfit), sans-serif' }}
      >
        <AuthSessionProvider>
          <AuthProvider>
            <SpeedInsights />
            {children}
            <Toaster
              position="top-right"
            />
          </AuthProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
